### ISSUE TITLE
Bring back option to configure target SNMP port

### ISSUE THREAD

**Issue by amotl** [wernerfred/check_synology#23]
Hi,

> A custom port can be specified by using `-p`. The default value is `161`.

I just discovered that the refactoring coming from #4/#19 dropped that feature to specify the target SNMP port number (#2), so we will have to bring it back when there is demand.

Also, after integrating #21, the Icinga configuration snippets will provide access to almost all parameters this program has to offer. However, the `-p` option is still missing there. Also depending on community demand, this can be added every time.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I just discovered that the refactoring coming from #4/#19 dropped that feature to specify the port number anyway, so we will have to bring it back when there is demand.

With kind regards,
Andreas.

**Comment by wernerfred** [comment]
I would like to have this functionality back in the script (still with default so that one does not have to use it). Adding it to the example files is a good idea, too 👍🏻

**Comment by amotl** [comment]
I will try to take care about it within one of the next iterations.

**Comment by wernerfred** [comment]
Current `README` also lists setting the port as an option. Should remove the part from the `README` in the meantime to not confuse new users?

**Comment by wernerfred** [comment]
As #31 now got merged i would like to publish a new release. But as the option to configure a target port is still a regression it would be a major version. So i am drafting a feature version bump as a pre release and release "normal" one as soon as this regression is solved

**Comment by amotl** [comment]
Dear Frederic,

I will re-add this option in the course of the next iterations. In the meanwhile, as I found out just yesterday, everyone can use a composite `host` syntax like `appliance.example.net:1161`. Easy SNMP accepts that as well ❤️ .

With kind regards,
Andreas.

**Comment by wernerfred** [comment]
Braindump (for future me or others): The corresponding option for the `easysnmp` `Session` should be `remote_port`.
