### ISSUE TITLE
Where do authkey privkey come from?

### ISSUE THREAD

**Issue by 2000teddy** [wernerfred/check_synology#3]
Hello wernerfred,

how do I get the authkey privkey for running the script. It was not explained where they come from.

So, please give me a hint.

Thanks in advance,
Chris

**Comment by wernerfred** [comment]
Hi @2000teddy,

as described in the README.md file "This plugin uses snmpv3 with MD5 + AES to check a lot of different values on your Synology DiskStation."

So the point is snmp in version 3. If you look up the definition you will learn about authentication and privacy in snmp verison 3 (https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol)

So you have to define the two values in the snmp settings on the host you want to check. If you want to check a synology you will find these in the settings under terminal & snmp. Make sure to check snmp v3.

**Comment by 2000teddy** [comment]
Hello wernerfred,

I was giving the account informations in the settings on terminal & snmp,
but there is no possibility there to generate a privkey or a authkey, only
username an password.

[image: image.png]

Also the synology documentation gives no hint for both of the mentioned
keys:
https://www.synology.com/en-us/knowledgebase/DSM/help/DSM/AdminCenter/system_snmp

It seems that synology doesn't maintain the key features?!


Best regards,
Mit besten Grüßen,

Christian Ullmann



Am So., 24. Nov. 2019 um 16:17 Uhr schrieb Frederic Werner <
notifications@github.com>:

**Comment by wernerfred** [comment]
You can set the username, the password (with protocol) and under snmp privacy you can set another password (with protocol).

With the current version of ```check_synology``` you have to choose ```MD5``` and ```AES```. Those two passwords are your auth(tentication)key and priv(acy)key.

Hope this helps, if not let me know your thoughts!
Cheers

![snmp_syno](https://user-images.githubusercontent.com/20406381/69664164-16a91d80-1088-11ea-8d50-563184afa6d5.JPG)

**Comment by wernerfred** [comment]
Closing this now, feel free to reopen if appropriate
