### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by dgoetz** [wernerfred/check_synology#7]
Python 2 was sunsetted on January 1st, 2020 and it gets more and more difficult to run it on modern systems, so having this plugin ported to Python 3 would be great. Thanks for considering!

**Comment by nbuchwitz** [comment]
@dgoetz please feel free to test #8

**Comment by dgoetz** [comment]
@nbuchwitz Thanks a lot, tests work great! :+1:

**Comment by wernerfred** [comment]
Will test it in my lab during weekend!
